import streamlit as st
import json
import os

# Configuration keys and state management

ADMIN_PASSWORD_HASH = "Admin#1976"

DEFAULT_MOCK_MATCHES = [
    {
        "country": "Europa",
        "league": "Liga Europa",
        "home": "Benfica",
        "away": "St. Gallen",
        "h_xg": 2.15,
        "a_xg": 0.90,
        "h_xga": 0.80,
        "a_xga": 1.85,
        "odd_1": 1.45,
        "odd_x": 4.50,
        "odd_2": 6.50,
        "odd_o05": 1.05,
        "odd_o15": 1.22,
        "odd_o25": 1.62,
        "odd_btts_yes": 1.75,
        "odd_btts_no": 2.00,
        "home_form": "V-D-V-D-V",
        "away_form": "D-E-V-D-E",
        "h2h_summary": "Últimos 3 confrontos: 2 Vitórias Benfica, 1 Empate (Média 3.3 golos/jogo)",
        "odd": 1.45,
        "market": "Vitória Casa (1)"
    },
    {
        "country": "Europa",
        "league": "Liga Europa",
        "home": "Anderlecht",
        "away": "Hammarby",
        "h_xg": 1.90,
        "a_xg": 0.95,
        "h_xga": 0.90,
        "a_xga": 1.40,
        "odd_1": 1.68,
        "odd_x": 3.80,
        "odd_2": 4.80,
        "odd_o05": 1.08,
        "odd_o15": 1.28,
        "odd_o25": 1.85,
        "odd_btts_yes": 1.80,
        "odd_btts_no": 1.95,
        "home_form": "V-E-V-V-D",
        "away_form": "E-V-D-E-V",
        "h2h_summary": "Primeiro confronto direto oficial registrado.",
        "odd": 1.68,
        "market": "Vitória Casa (1)"
    },
    {
        "country": "Europa",
        "league": "Liga Europa",
        "home": "PAOK",
        "away": "Dynamo Kyiv",
        "h_xg": 1.75,
        "a_xg": 1.20,
        "h_xga": 0.85,
        "a_xga": 1.30,
        "odd_1": 1.95,
        "odd_x": 3.40,
        "odd_2": 3.90,
        "odd_o05": 1.06,
        "odd_o15": 1.30,
        "odd_o25": 1.90,
        "odd_btts_yes": 1.72,
        "odd_btts_no": 2.05,
        "home_form": "V-V-V-E-D",
        "away_form": "V-D-V-E-E",
        "h2h_summary": "Últimos 2 jogos: 1 Vitória PAOK, 1 Vitória Dynamo Kyiv (Média 2.5 golos/jogo)",
        "odd": 1.72,
        "market": "Ambas Marcam (BTTS Sim)"
    },
    {
        "country": "Europa",
        "league": "Liga Conferência",
        "home": "Brann",
        "away": "U Cluj",
        "h_xg": 1.95,
        "a_xg": 0.80,
        "h_xga": 0.75,
        "a_xga": 1.50,
        "odd_1": 1.42,
        "odd_x": 4.60,
        "odd_2": 7.00,
        "odd_o05": 1.04,
        "odd_o15": 1.20,
        "odd_o25": 1.65,
        "odd_btts_yes": 1.88,
        "odd_btts_no": 1.85,
        "home_form": "V-V-V-D-V",
        "away_form": "E-D-D-V-E",
        "h2h_summary": "Sem históricos recentes nos últimos 5 anos.",
        "odd": 1.42,
        "market": "Vitória Casa (1)"
    },
    {
        "country": "Europa",
        "league": "Liga Conferência",
        "home": "Nordsjælland",
        "away": "GAIS",
        "h_xg": 2.05,
        "a_xg": 1.10,
        "h_xga": 1.10,
        "a_xga": 1.60,
        "odd_1": 1.60,
        "odd_x": 4.00,
        "odd_2": 5.20,
        "odd_o05": 1.05,
        "odd_o15": 1.22,
        "odd_o25": 1.55,
        "odd_btts_yes": 1.65,
        "odd_btts_no": 2.10,
        "home_form": "V-E-D-V-V",
        "away_form": "V-V-E-D-D",
        "h2h_summary": "Últimos 2 amigáveis: 1 Vitória Nordsjælland, 1 Empate.",
        "odd": 1.55,
        "market": "Total +2.5 Golos"
    },
    {
        "country": "Europa",
        "league": "Liga Conferência",
        "home": "CFR Cluj",
        "away": "Alashkert",
        "h_xg": 1.70,
        "a_xg": 0.70,
        "h_xga": 0.80,
        "a_xga": 1.70,
        "odd_1": 1.50,
        "odd_x": 4.20,
        "odd_2": 6.20,
        "odd_o05": 1.05,
        "odd_o15": 1.26,
        "odd_o25": 1.80,
        "odd_btts_yes": 1.95,
        "odd_btts_no": 1.78,
        "home_form": "V-D-V-V-E",
        "away_form": "D-D-E-V-D",
        "h2h_summary": "Últimos 2 confrontos: 2 Vitórias CFR Cluj (Sem golos sofridos).",
        "odd": 1.50,
        "market": "Vitória Casa (1)"
    },
    {
        "country": "Europa",
        "league": "Liga Conferência",
        "home": "Gent",
        "away": "LNZ Cherkasy",
        "h_xg": 2.20,
        "a_xg": 0.85,
        "h_xga": 1.05,
        "a_xga": 1.75,
        "odd_1": 1.48,
        "odd_x": 4.40,
        "odd_2": 6.00,
        "odd_o05": 1.04,
        "odd_o15": 1.20,
        "odd_o25": 1.60,
        "odd_btts_yes": 1.75,
        "odd_btts_no": 1.98,
        "home_form": "V-V-D-V-V",
        "away_form": "D-E-V-D-E",
        "h2h_summary": "Sem histórico oficial registrado.",
        "odd": 1.60,
        "market": "Total +2.5 Golos"
    },
    {
        "country": "Europa",
        "league": "Liga Conferência",
        "home": "Shkëndija",
        "away": "Bravo",
        "h_xg": 1.65,
        "a_xg": 0.82,
        "h_xga": 0.70,
        "a_xga": 1.35,
        "odd_1": 1.55,
        "odd_x": 3.90,
        "odd_2": 5.80,
        "odd_o05": 1.07,
        "odd_o15": 1.32,
        "odd_o25": 1.95,
        "odd_btts_yes": 1.90,
        "odd_btts_no": 1.82,
        "home_form": "V-E-V-D-V",
        "away_form": "E-D-V-E-D",
        "h2h_summary": "Primeira partida na competição.",
        "odd": 1.55,
        "market": "Vitória Casa (1)"
    },
    {
        "country": "Europa",
        "league": "Liga Europa",
        "home": "Midtjylland",
        "away": "Beşiktaş",
        "h_xg": 1.80,
        "a_xg": 1.60,
        "h_xga": 1.30,
        "a_xga": 1.40,
        "odd_1": 2.25,
        "odd_x": 3.50,
        "odd_2": 2.95,
        "odd_o05": 1.04,
        "odd_o15": 1.22,
        "odd_o25": 1.65,
        "odd_btts_yes": 1.55,
        "odd_btts_no": 2.30,
        "home_form": "V-V-D-E-V",
        "away_form": "V-D-V-V-E",
        "h2h_summary": "Últimos 2 jogos: 1 Vitória Midtjylland, 1 Vitória Beşiktaş (Ambas Marcam Sim em todos os jogos).",
        "odd": 1.55,
        "market": "Ambas Marcam (BTTS Sim)"
    },
    {
        "country": "Polónia",
        "league": "Ekstraklasa",
        "home": "GKS Katowice",
        "away": "Žilina",
        "h_xg": 1.68,
        "a_xg": 1.10,
        "h_xga": 1.00,
        "a_xga": 1.55,
        "odd_1": 1.72,
        "odd_x": 3.70,
        "odd_2": 4.40,
        "odd_o05": 1.06,
        "odd_o15": 1.28,
        "odd_o25": 1.75,
        "odd_btts_yes": 1.70,
        "odd_btts_no": 2.05,
        "home_form": "V-E-V-V-D",
        "away_form": "D-V-E-D-V",
        "h_summary": "Últimos 4 jogos: 2 Vitórias GKS Katowice, 1 Empate, 1 Vitória Žilina.",
        "odd": 1.72,
        "market": "Vitória Casa (1)"
    }
]


def _get_secret(key_name: str, default_val: str = "") -> str:
    """Retrieve secret from Streamlit Cloud secrets, environment variable, or fallback default."""
    try:
        if hasattr(st, "secrets") and key_name in st.secrets:
            val = str(st.secrets[key_name]).strip()
            if val:
                return val
    except Exception:
        pass
    return os.environ.get(key_name, default_val)

def init_session_state():
    """Ensure all required session state variables exist."""
    defaults = {
        "app_started": False,
        "confirm_exit": False,
        "matches_data": [],
        "analysed_results": [],
        "filtered_matches": [],
        "gemini_key": _get_secret("GEMINI_API_KEY", "AIzaSyCWnt9Foq226tOF7IG4JSx8lVLvqL1biq8"),
        "odds_provider": "The Odds API (the-odds-api.com)",
        "odds_api_key": _get_secret("ODDS_API_KEY", "0679363fc9fed7e8be5414173c5c1b8a"),
        "api_football_key": _get_secret("API_FOOTBALL_KEY", ""),
        "ngrok_key": _get_secret("NGROK_AUTHTOKEN", "3Gtx36ExMiXQAki5sFVrwTmOoC2_4CEFuYvnLQjUX5jYWcJyA"),
        "email_sender": _get_secret("EMAIL_SENDER", ""),
        "email_password": _get_secret("EMAIL_PASSWORD", ""),
        "is_admin": False,
        "active_tab": "🔍 Obter Jogos (Odds API / OddsPortal / Gemini)",
        "last_ingestion_log": ""
    }

    for key, value in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = value
